### ISSUE TITLE
Update Releases section to contain notes for each release.

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit.dev#1170]
You should be able to see 2.0 and 3.0 release notes and upgrade guides no matter which version of the docs you have selected.

**Comment by AndrewJakubowicz** [comment]
This was tested in https://github.com/lit/lit.dev/pull/1178, but I'm not sure if we want to have both.

Maybe only both Releases in the v3 version of the docs?

**Comment by augustjk** [comment]
Low effort, could add link to Lit 2 upgrade guide at top of Lit 3 upgrade guide.

We should also add to the document title "Lit 3 upgrade guide" rather than "Upgrade guide".

I think it might be easy enough to do:

lit.dev v3
Releases
 - Lit 3 upgrade guide
 - Lit 2 upgrade guide (either copy or link to /v2/upgrade-guide)

lit.dev v2
Releases
 - Lit 2 upgrade guide

**Comment by AndrewJakubowicz** [comment]
This issue ended up being resolved via @augustjk's suggestion of adding a link to the top.

<img width="841" alt="Screenshot 2023-10-09 at 11 10 23 AM" src="https://github.com/lit/lit.dev/assets/15080861/978ab7b7-629b-41cb-8fe6-71049f72e754">
