### ISSUE TITLE
Dark Mode trigger icons are reversed if already in prefers-color-scheme(dark)

### ISSUE THREAD

**Issue by GeorgeWL** [lit/lit.dev#1318]
I think it should be a moon icon to say "switch to dark" and sun icon for "switch to light" but they appear to be reversed

![Screenshot_2024-03-23-14-34-38-62_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/lit/lit.dev/assets/5931248/9ea824f0-bebc-4fca-ad74-f56833090008)

![Screenshot_2024-03-23-14-34-30-63_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/lit/lit.dev/assets/5931248/d1ffc698-5075-4211-b07c-5fa3cfd31f68)

**Comment by e111077** [comment]
Hmm yeah I had this issue, and I wasn't totally sure which to go with. Currently the icon shows the current state:

sun/moon -> currently follow system
sun -> currently force light mode
moon -> currently force dark mode

and the other option is to show "what's next if you click this", but since it's a trinary toggle of "force light" "force dark" "follow system" I thought it would be a bit weird to show the "if you click this, the icon shows you the next state". In other sites, I've done a segmented button like on https://material-web.dev/, but we don't have the space to do that here

**Comment by e111077** [comment]
I'll probably make this an icon-button <select>

**Comment by justinfagnani** [comment]
@e111077 I have a theme selection element that has a dropdown for light/dark/auto that I can dig up.

**Comment by e111077** [comment]
live example of dropdown:

[pr1320-a53c385---lit-dev-5ftespv5na-uc.a.run.app](https://pr1320-a53c385---lit-dev-5ftespv5na-uc.a.run.app/)
