### ISSUE TITLE
Playground example "not assignable to parameter" type checker issue

### ISSUE THREAD

**Issue by AndrewJakubowicz** [lit/lit.dev#429]
## Issue

See playground example in https://lit.dev/docs/components/events/?mods=search#when-to-dispatch-an-event

There is a syntax error being displayed in the playground example: 
![image](https://user-images.githubusercontent.com/15080861/128757369-a08e3d22-0571-4977-aad3-2977a7b2a297.png)

I am not sure why this example has a syntax error since copying it directly into a playground doesn't reproduce the error,

## Completion criteria

 - Documentation example shouldn't have typescript error.

**Comment by aomarks** [comment]
This is fixed since https://github.com/lit/lit.dev/pull/441.

This was the error that was being displayed before:

```
Argument of type 'MyDispatcher' is not assignable to parameter of type 'ReactiveElement | ClassElement'. Type 'MyDispatcher' is missing the following properties from type 'ReactiveElement': __updatePromise, __pendingConnectionPromise, __enableConnection, isUpdatePending, and 8 more.
```

I'm not *exactly* sure why, but I think it was very likely due to not loading the correct version of some typings file somewhere in the tree, which is what the latest version of playground addresses.
