### ISSUE TITLE
Unify home-page JS/TS switch with samples switch

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit.dev#490]
Should the main example on the homepage use the same JS/TS preference as the other samples? And should the switch be styled the same to be consistent?

**Comment by aomarks** [comment]
Switch should be styled the same yeah.

I'm not 100% sure about making it sync'd with the localStorage setting though. I would be concerned that somebody would toggle it on the homepage just because it's a fun / interesting thing to do, and then not realize they were missing out on the TypeScript docs as our default/recommended? Just sort of feels like an independent toy on the homepage, I guess.

**Comment by AndrewJakubowicz** [comment]
Regarding our recommended option being Typescript, we could also save the state in sessionStorage so it's a little less sticky.  I have no preference since the switch is pretty easy (and fun) to change.
