### ISSUE TITLE
"Names controller" example does not work

### ISSUE THREAD

**Issue by e111077** [lit/lit.dev#559]
The Names Controller example is giving me fetch errors:

https://lit.dev/docs/composition/controllers/#asynchronous-tasks

Looks like CORS + playground
![image](https://user-images.githubusercontent.com/5981958/137049243-1e43632d-262a-4c52-b9ff-5c87d744dca1.png)

**Comment by augustjk** [comment]
I just came across this again.

Some potential free API sources that won't require API keys:
https://swapi.dev/
https://pokeapi.co/

Or as Arthur suggested, creating our own endpoint that serves data could be an option, or a mock `fetch` function that just resolves with a response after some random timeout could be enough for demonstration purposes too.

**Comment by arthurevans** [comment]
Yeah, my concern about using something like that is that if we rely on a free service, it could be terminated or rate-limited at any time, and then we end up back where we are today.

**Comment by augustjk** [comment]
Yes that's certainly valid. swapi.dev is actually a fork as swapi.co went down. The current maintainer does mention that they decided to fork because the original api was used in a lot of projects and tutorials. pokeapi.co has been around since 2018 and has sizable community support. These are no guarantee of future longevity though.

I think it's pretty low-effort to do a swap. I'd be happy to whip something up if you don't mind.

**Comment by arthurevans** [comment]
That would be awesome!
