### ISSUE TITLE
API docs: queryAssignedNodes

### ISSUE THREAD

**Issue by djlauk** [lit/lit.dev#670]
I was looking at the [API docs for some decorators](https://lit.dev/docs/api/decorators) today and noticed, that the return type in the signature looks different for `queryAssignedNodes` and the other decorators.
I also noticed that the example code and docs disagree about the type annotation: Example code uses `Array<HTMLElement>`, docs say to use `Array<Node>`.

Side note:
Having a look at [page.json](https://github.com/lit/lit.dev/blob/main/packages/lit-dev-api/api-data/lit-2/pages.json) it looks like the return type in the signature for [queryAssignedNodes](https://github.com/lit/lit.dev/blob/main/packages/lit-dev-api/api-data/lit-2/pages.json#L7419) is provided explicitly, while for [queryAssignedElements](https://github.com/lit/lit.dev/blob/main/packages/lit-dev-api/api-data/lit-2/pages.json#L7308) seems to be inferred from reflection.

**Comment by AndrewJakubowicz** [comment]
Thanks for this issue - you found a type signature bug in the example code. You're right about the disagreeing signature. `queryAssignedNodes` should use Array<Node>. Sorry!

Regarding the return types.

`@queryAssignedNodes()` predated `@queryAssignedElements()` so it currently contains fallback logic and handles two different argument formats:

Legacy:
 - `@queryAssignedNodes(/* slot */ '', /* flatten */ false, /* selector */ '.itemClass')`
 - This legacy decorator is returning `Array<HTMLElement>`
Recommended:
 - `@queryAssignedNodes({ slot: '', flatten: false })`
 - Recommended usage returns `Array<Node>`

In order to write a valid TypeScript signature for the overloads in `queryAssignedNodes`, TypeScript requires decorators to return `any|void`. I.e.

`type TSDecoratorReturnType = void | any;`

That's why `queryAssignedNodes` has a different return type in the generated docs than the other decorators, including `query`, and `queryAll`.

**Comment by AndrewJakubowicz** [comment]
Closing issue as I believe the major issue is mismatch in code example which is fixed.

In the future when the legacy queryAssignedNodes behavior is removed, it will have a type signature that is similar to the other decorators. I guess we could explicitly type all the decorators with `any|void` as well.
