### ISSUE TITLE
How to understand this sentence about live directive?

### ISSUE THREAD

**Issue by novenn** [lit/lit.dev#854]
How to understand this sentence of live directive's summary, is this means: if the attribute or propery is differs from live dom value, then set the attribute or property value to live dom value ?

but the description of live directive says: "if you want to overwrite the DOM value with the bound value no matter what—use the `live()` directive"

This confuses me；

![image](https://user-images.githubusercontent.com/24600592/172038753-762d0247-0675-4cd1-aaef-147f8f280cb0.png)

sorry， but I'm not an English developer

**Comment by augustjk** [comment]
The `live()` directive makes sure that the _checking_ whether it needs to update happens against the live DOM value, then sets the attribute/property to the bound expression, overwriting the current DOM value.

Perhaps this example helps clarify it https://lit.dev/playground/#sample=examples/directive-live

If you make changes to the text in the 2nd and 3rd input, the DOM values of those inputs change so they are out of sync with `this.data.value`. If you then click commit, the 2nd one with the `live()` directive detects that the current DOM value is different than what's in `this.data.value` and updates, whereas the 3rd input thinks that because `this.data.value` never changed it doesn't need to update.

**Comment by novenn** [comment]
> The `live()` directive makes sure that the _checking_ whether it needs to update happens against the live DOM value, then sets the attribute/property to the bound expression, overwriting the current DOM value.
> 
> Perhaps this example helps clarify it https://lit.dev/playground/#sample=examples/directive-live
> 
> If you make changes to the text in the 2nd and 3rd input, the DOM values of those inputs change so they are out of sync with `this.data.value`. If you then click commit, the 2nd one with the `live()` directive detects that the current DOM value is different than what's in `this.data.value` and updates, whereas the 3rd input thinks that because `this.data.value` never changed it doesn't need to update.

thanks!!! 

I misunderstood I thought "attribute/properties" here belonged to Lit components, but in fact they belonged to input elements.


![image](https://user-images.githubusercontent.com/24600592/172512899-312061f1-774a-411d-a953-2517f826c497.png)

**Comment by e111077** [comment]
Assigning to @arthurevans in case this warrants a reword
